export const POST_PDT = "POST_PRODUCTS"
export const GET_PDT = "GET_PRODUCTS"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_BRANDS = "GET_BRANDS"
export const GET_PAGINATE = "GET_PAGINATE"
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const GET_DET = "GET_DETAILS"
export const GET_NAM = "GET_NAME"
export const POST_PAGO = "POST_PAGO"
export const POST_USER = "CREATE_USER_SUCCESS"
export const UPD_USER = "UPDATE_SUCCESS"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CLEAR_CART = "CLEAR_CART"
export const SET_QUANTITY = "SET_QUANTITY"
export const VALIDATE_SUCCESS_ORDER = "VALIDATE_SUCCESS_ORDER"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const GET_ORD = "GET_ORDER_SUCCESS"
export const LOGOUT = "LOGOUT"
export const GET_USER = "GET_USER"
export const SELL = "SELL_ORDER_SUCCES"


