export const POST_PDT = "POST_PRODUCTS"
export const GET_PDT = "GET_PRODUCTS"
export const GET_NAME_PRODUCTS ="GET_NAME_PRODUCTS"
export const GET_CATEGORIS = "GET_CATEGORIS"
export const GET_PAGINATE = "GET_PAGINATE"
export const GET_DET = "GET_DATE"